# 其他误差SARAR

探究高维SARAR在不同误差分布下的表现。


## 覆盖率

```{r include=FALSE}
CP <- function(ns,indexs,error){
  # ===================修改参数====================
  # error = 1 # 1:N(0,1) 2:N(0,0.75) 3:t(5) 4:chi2(4)
  # ns = c(100,225,900)
  # indexs = c(0,0.14,0.16,0.24,0.4)
  # ===================定义结果====================
  c = c(3,4,5)
  CPs = matrix(NA,length(indexs)*3,length(ns)*3)
  colnames(CPs) = rep(ns,each=3)
  rownames(CPs) = rep(indexs,each=3)
  # ===================计算覆盖率==================
  i = 0
  for(n in ns){
    i = i + 3
    j = 0
    for(index in indexs){
      j = j + 3
      # 计算p
      ps = round(c*n^index)
  
      q1 = qchisq(0.95,ps+3)
      q2 = qnorm(0.975)
      # 读取数据
      EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
      MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
      nsim = dim(EL)[1]
      # 编制分位数矩阵
      Q1 = matrix(q1,nsim,3,byrow=TRUE)
      Q2 = matrix(q2,nsim,3)
      # 计算覆盖率
      CP1 = colSums(EL<=Q1)/nsim
      CP2 = colSums(abs(MEL)<=Q2)/nsim
  
      CPs[(j-2):j,i-2] = ps
      CPs[(j-2):j,i-1] = CP1
      CPs[(j-2):j,i  ] = CP2
    }
  }
  
  return(CPs)
}

```

```{r include=FALSE}
library(kableExtra)
```

- $N(0,1)$误差
```{r echo=FALSE}
ns = c(100,400,900)
indexs = c(0,0.14,0.24,0.3,0.4)

error = 1
cp = CP(ns,indexs,error)
kable(cp, "html", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F) 

```

- $N(0,0.75)$误差

```{r echo=FALSE}
error = 2
cp = CP(ns,indexs,error)
kable(cp, "html", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F) 
```

- $t(5)$误差
```{r echo=FALSE}
error = 3
cp = CP(ns,indexs,error)
kable(cp, "html", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = F) 
```

- $\chi^2(4)$误差
```{r echo=FALSE}
error = 4
cp = CP(ns,indexs,error)
kable(cp, "html", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive","bordered"), full_width = F) 
```

## 分位数图

```{r include=FALSE}
MEL_figureQQ <- function(MEL){
  m = 50                                # 分位数个数
  as = (1:m-0.5)/m                      # 名义水平
  # 绘制正态QQ图
  qas <- qnorm(as)                      # 正态分布的分位数点
  c1 = sort(MEL[,1])[ceiling(as*nsim)]  # mel的分位数点
  c2 = sort(MEL[,2])[ceiling(as*nsim)]
  c3 = sort(MEL[,3])[ceiling(as*nsim)]
  plot(qas,qas,xaxs = 'i', yaxs = 'i',
       yaxt = 'n', ann = F, type = 'l')
  axis(2, las = 1)
  title(main = paste0('Norm n = ',n,' index = ',index),
        xlab = 'Normal quantile', ylab = 'MEL quantile')
  lines(qas,c1,type='l',lty=1,lwd=1.5,col='blue1')
  lines(qas,c2,type='l',lty=3,lwd=1.5,col='aquamarine4')
  lines(qas,c3,type='l',lty=5,lwd=1.5,col='brown2')
  points(qnorm(0.95),qnorm(0.95),pch=5)
}
```


```{r include=FALSE}
EL_figureQQ <- function(EL){
  # 绘制卡方QQ图
  qas <- seq(0,120,5)                     # 卡方的分位数点
  c1 = sort(EL[,1])[ceiling(as*nsim)]    # mel的分位数点
  c2 = sort(EL[,2])[ceiling(as*nsim)]
  c3 = sort(EL[,3])[ceiling(as*nsim)]
  plot(qas,qas,xaxs = 'i', yaxs = 'i',
       xlim =c(min(qchisq(as,ps[1]+3)), max(qchisq(as,ps[3]+3))),
       ylim =c(min(qchisq(as,ps[1]+3)), max(qchisq(as,ps[3]+3))),
       yaxt = 'n', ann = F, type = 'l')
  axis(2, las = 1)
  title(main = paste0('ChiS n = ',n,' index = ',index),
        xlab = 'ChiSquare quantile', ylab = 'EL quantile')
  lines(qchisq(as,ps[1]+3),c1,type='l',lty=1,lwd=1.5,col='blue1')
  lines(qchisq(as,ps[2]+3),c2,type='l',lty=3,lwd=1.5,col='aquamarine4')
  lines(qchisq(as,ps[3]+3),c3,type='l',lty=5,lwd=1.5,col='brown2')
  points(qchisq(0.95,ps[1]+3),qchisq(0.95,ps[1]+3),pch=5,col='blue1')
  points(qchisq(0.95,ps[2]+3),qchisq(0.95,ps[2]+3),pch=5,col='aquamarine4')
  points(qchisq(0.95,ps[3]+3),qchisq(0.95,ps[3]+3),pch=5,col='brown2')
}
```

### $N(0,1)$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 1
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
```

### $N(0,1)$误差 MEL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 1
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```


### $N(0,0.75)$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 2
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
```


### $N(0,0.75)$误差 MEL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 2
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```

### $t(5)$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 3
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
```

### $t(5)$误差 MEL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 3
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```


### $\chi^2(4)$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 4
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
``` 

### $\chi^2(4)$误差 MEL
```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 4
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```

