# 分位数全貌图

探究高维SARAR在不同误差分布下整体表现。

## 对比图

此处仅展示误差服从标准正态下的分位数图。

```{r include=FALSE}
SARAR_QQ2 <- function(EL, MEL){
  par(mfrow = c(1, 2))
  # cat(n,index,max(EL),max(MEL),'\n')
  
  # 卡方分位数图
  x <- seq(-max(EL),max(EL),5)                 # 卡方的分位数点
  c1 = sort(EL[,1])[ceiling(as*nsim)]   # mel的分位数点
  c2 = sort(EL[,2])[ceiling(as*nsim)]
  c3 = sort(EL[,3])[ceiling(as*nsim)]
  plot(x,x,xaxs = 'i', yaxs = 'i',
       xlim =c(min(c1), max(c3)),
       ylim =c(min(c1), max(c3)),
       yaxt = 'n', ann = F, type = 'l')
  axis(2, las = 1)
  title(main = paste0('ChiS n = ',n,' index = ',index),
        xlab = 'ChiSquare quantile', ylab = 'EL quantile')
  lines(qchisq(as,ps[1]+3),c1,type='l',lty=1,lwd=1.5,col='blue1')
  lines(qchisq(as,ps[2]+3),c2,type='l',lty=3,lwd=1.5,col='aquamarine4')
  lines(qchisq(as,ps[3]+3),c3,type='l',lty=5,lwd=1.5,col='brown2')
  points(qchisq(0.95,ps[1]+3),qchisq(0.95,ps[1]+3),pch=5,col='blue1')
  points(qchisq(0.95,ps[2]+3),qchisq(0.95,ps[2]+3),pch=5,col='aquamarine4')
  points(qchisq(0.95,ps[3]+3),qchisq(0.95,ps[3]+3),pch=5,col='brown2')
  
  # 正态分位数图
  m = 50                                # 分位数个数
  as = (1:m-0.5)/m                      # 名义水平
  qas <- qnorm(as)                      # 正态分布的分位数点
  c1 = sort(MEL[,1])[ceiling(as*nsim)]  # mel的分位数点
  c2 = sort(MEL[,2])[ceiling(as*nsim)]
  c3 = sort(MEL[,3])[ceiling(as*nsim)]
  plot(x,x,xaxs = 'i', yaxs = 'i',
       xlim =c(min(c1), max(c3)),
       ylim =c(min(c1), max(c3)),
       yaxt = 'n', ann = F, type = 'l')
  axis(2, las = 1)
  title(main = paste0('Norm n = ',n,' index = ',index),
        xlab = 'Normal quantile', ylab = 'MEL quantile')
  lines(qas,c1,type='l',lty=1,lwd=1.5,col='blue1')
  lines(qas,c2,type='l',lty=3,lwd=1.5,col='aquamarine4')
  lines(qas,c3,type='l',lty=5,lwd=1.5,col='brown2')
  points(qnorm(0.95),qnorm(0.95),pch=5)
}
```

```{r include=FALSE}
ns = c(100,400,900)
indexs = c(0,0.14,0.24,0.3,0.4)
```

```{r echo=FALSE, fig.height=3.7, fig.width=6.7}
## 绘制EL与MEL对比图
error = 1
for(n in ns){
  for(index in indexs){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    SARAR_QQ2(EL=EL,MEL=MEL)
  }
}
```


## 分位数图


```{r include=FALSE}
EL_figureQQ <- function(EL){
  # 卡方分位数图
  x <- seq(-max(EL),max(EL),1)          # 卡方的分位数点
  c1 = sort(EL[,1])[ceiling(as*nsim)]   # mel的分位数点
  c2 = sort(EL[,2])[ceiling(as*nsim)]
  c3 = sort(EL[,3])[ceiling(as*nsim)]
  plot(x,x,xaxs = 'i', yaxs = 'i',
       xlim =c(min(c1), max(c3)),
       ylim =c(min(c1), max(c3)),
       yaxt = 'n', ann = F, type = 'l')
  axis(2, las = 1)
  title(main = paste0('ChiS n = ',n,' index = ',index),
        xlab = 'ChiSquare quantile', ylab = 'EL quantile')
  lines(qchisq(as,ps[1]+3),c1,type='l',lty=1,lwd=1.5,col='blue1')
  lines(qchisq(as,ps[2]+3),c2,type='l',lty=3,lwd=1.5,col='aquamarine4')
  lines(qchisq(as,ps[3]+3),c3,type='l',lty=5,lwd=1.5,col='brown2')
  points(qchisq(0.95,ps[1]+3),qchisq(0.95,ps[1]+3),pch=5,col='blue1')
  points(qchisq(0.95,ps[2]+3),qchisq(0.95,ps[2]+3),pch=5,col='aquamarine4')
  points(qchisq(0.95,ps[3]+3),qchisq(0.95,ps[3]+3),pch=5,col='brown2')
}
```

```{r include=FALSE}
MEL_figureQQ <- function(MEL){
  # 正态分位数图
  x <- seq(-max(MEL),max(MEL),1)          # 卡方的分位数点
  m = 50                                # 分位数个数
  as = (1:m-0.5)/m                      # 名义水平
  qas <- qnorm(as)                      # 正态分布的分位数点
  c1 = sort(MEL[,1])[ceiling(as*nsim)]  # mel的分位数点
  c2 = sort(MEL[,2])[ceiling(as*nsim)]
  c3 = sort(MEL[,3])[ceiling(as*nsim)]
  plot(x,x,xaxs = 'i', yaxs = 'i',
       xlim =c(min(c1), max(c3)),
       ylim =c(min(c1), max(c3)),
       yaxt = 'n', ann = F, type = 'l')
  axis(2, las = 1)
  title(main = paste0('Norm n = ',n,' index = ',index),
        xlab = 'Normal quantile', ylab = 'MEL quantile')
  lines(qas,c1,type='l',lty=1,lwd=1.5,col='blue1')
  lines(qas,c2,type='l',lty=3,lwd=1.5,col='aquamarine4')
  lines(qas,c3,type='l',lty=5,lwd=1.5,col='brown2')
  points(qnorm(0.95),qnorm(0.95),pch=5)
}
```


### $N(0,1)$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 1
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
```

### $N(0,1)$误差 MEL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 1
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```


### $N(0,0.75)$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 2
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
```


### $N(0,0.75)$误差 MEL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 2
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```

### $t(5)$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 3
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
```

### $t(5)$误差 MEL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 3
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```


### $\chi^2(4)-4$误差 EL

```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 4
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    EL = read.csv(paste0('data/2022QinYongsong/EL',error,n,index,'.csv'))
    nsim = dim(EL)[1]
    EL_figureQQ(EL)
  }
}
``` 

### $\chi^2(4)-4$误差 MEL
```{r echo=FALSE, fig.height=3.2, fig.width=9}
error = 4
for(index in indexs){
  par(mfrow = c(1, length(ns)))
  for(n in ns){
    c = c(3,4,5)
    ps = round(c*n^index)
    MEL = read.csv(paste0('data/2022QinYongsong/MEL',error,n,index,'.csv'))
    nsim = dim(MEL)[1]
    MEL_figureQQ(MEL)
  }
}
```

