---
title: "2009ChenSongxi QQ图"
author: "Tan Jay"
date: '2022-09-27'
output:
  word_document: default
  pdf_document: default
  html_document: default
---
```{r echo=FALSE, fig.height=3, fig.width=9}
nsim = 500            # 模拟次数
m = 50               # 分位数个数
as = (1:m-0.5)/m
qas <- qnorm(as)                   # 正态分布的分位数点

figureQQ <- function(n,C){
  c1 = sort(C[,1])[ceiling(as*nsim)] # mel的分位数点
  c2 = sort(C[,2])[ceiling(as*nsim)]
  c3 = sort(C[,3])[ceiling(as*nsim)]
  x = seq(-3,3,0.01)
  plot(x,x,
       xlim = c(-3,3), ylim = c(-3,3),
       xaxs = 'i', yaxs = 'i',
       yaxt = 'n',
       ann = F, type = 'l')
  axis(2, las = 1)
  title(main = paste0('Normal n = ',n),
        xlab= 'Normal quantile', ylab = 'EL quantile',
        line = 2)
  lines(qas,c1,type='l',lty=1,lwd=1.5,col='blue1')
  lines(qas,c2,type='l',lty=3,lwd=1.5,col='aquamarine4')
  lines(qas,c3,type='l',lty=5,lwd=1.5,col='brown2')
}
```


```{r echo=FALSE, fig.height=3, fig.width=9}
par(mfrow = c(1, 3))
C = read.csv("EL20020.csv")
figureQQ(n=200,C=C)

C = read.csv("EL40030.csv")
figureQQ(n=400,C=C)

C = read.csv("EL80040.csv")
figureQQ(n=800,C=C)
```

```{r echo=FALSE, fig.height=3, fig.width=9}
par(mfrow = c(1, 3))

C = read.csv("EL20043.csv")
figureQQ(n=200,C=C)

C = read.csv("EL40058.csv")
figureQQ(n=400,C=C)

C = read.csv("EL80072.csv")
figureQQ(n=800,C=C)
```

